'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  info: () => ipcRenderer.invoke('info'),
  search: opts => ipcRenderer.invoke('search', opts),
  get: uid => ipcRenderer.invoke('get', uid),
  aiStatus: () => ipcRenderer.invoke('ai-status'),
  setAiSearch: isOn => ipcRenderer.invoke('set-ai-search', isOn),
  onAi: cb => ipcRenderer.on('ai', (_e, status) => cb(status)),
  gameQuestions: (count, includeOwn) => ipcRenderer.invoke('game-questions', count, includeOwn),
  lists: () => ipcRenderer.invoke('lists'),
  createList: name => ipcRenderer.invoke('create-list', name),
  renameList: (listId, name) => ipcRenderer.invoke('rename-list', listId, name),
  deleteList: listId => ipcRenderer.invoke('delete-list', listId),
  addToList: (listId, uid) => ipcRenderer.invoke('add-to-list', listId, uid),
  removeFromList: (listId, uid) => ipcRenderer.invoke('remove-from-list', listId, uid),
  reorderList: (listId, uidsInOrder) => ipcRenderer.invoke('reorder-list', listId, uidsInOrder),
  listQuestions: listId => ipcRenderer.invoke('list-questions', listId),
  listIdsContaining: uid => ipcRenderer.invoke('list-ids-containing', uid),
  startPlayGame: settings => ipcRenderer.invoke('start-play-game', settings),
  submitPlayAnswer: (gameId, answer) => ipcRenderer.invoke('submit-play-answer', gameId, answer),
  setPlayAnswerCorrect: (gameId, position, isCorrect) => ipcRenderer.invoke('set-play-answer-correct', gameId, position, isCorrect),
  finishPlayGame: gameId => ipcRenderer.invoke('finish-play-game', gameId),
  deletePlayGame: gameId => ipcRenderer.invoke('delete-play-game', gameId),
  playGames: () => ipcRenderer.invoke('play-games'),
  playGameAnswers: gameId => ipcRenderer.invoke('play-game-answers', gameId),
  partyOpen: () => ipcRenderer.invoke('party-open'),
  partyStartRound: round => ipcRenderer.invoke('party-start-round', round),
  partySkipWait: () => ipcRenderer.invoke('party-skip-wait'),
  partyPause: () => ipcRenderer.invoke('party-pause'),
  partyResume: () => ipcRenderer.invoke('party-resume'),
  partySetScreen: screen => ipcRenderer.invoke('party-set-screen', screen),
  partyCloseAnswers: () => ipcRenderer.invoke('party-close-answers'),
  partyNext: () => ipcRenderer.invoke('party-next'),
  partyFinishRound: () => ipcRenderer.invoke('party-finish-round'),
  partySetCorrect: (playerId, position, isCorrect) => ipcRenderer.invoke('party-set-correct', playerId, position, isCorrect),
  partyKick: playerId => ipcRenderer.invoke('party-kick', playerId),
  partyAnnounce: text => ipcRenderer.invoke('party-announce', text),
  partySetReactionsOn: areOn => ipcRenderer.invoke('party-set-reactions-on', areOn),
  onPartyReaction: cb => {
    const listener = (_e, reaction) => cb(reaction);
    ipcRenderer.on('party-reaction', listener);
    return () => ipcRenderer.removeListener('party-reaction', listener);
  },
  partyBackToLobby: keepScores => ipcRenderer.invoke('party-back-to-lobby', keepScores),
  partyClose: () => ipcRenderer.invoke('party-close'),
  partyResults: () => ipcRenderer.invoke('party-results'),
  resetPartyResults: () => ipcRenderer.invoke('reset-party-results'),
  pointSystems: () => ipcRenderer.invoke('point-systems'),
  newPointSystem: () => ipcRenderer.invoke('new-point-system'),
  gameTemplates: () => ipcRenderer.invoke('game-templates'),
  saveGameTemplate: template => ipcRenderer.invoke('save-game-template', template),
  deleteGameTemplate: id => ipcRenderer.invoke('delete-game-template', id),
  savePointSystem: system => ipcRenderer.invoke('save-point-system', system),
  deletePointSystem: id => ipcRenderer.invoke('delete-point-system', id),
  partyProfiles: () => ipcRenderer.invoke('party-profiles'),
  clearPartyProfilePin: name => ipcRenderer.invoke('clear-party-profile-pin', name),
  deletePartyProfile: (name, options) => ipcRenderer.invoke('delete-party-profile', name, options),
  onPartyResults: cb => {
    const listener = (_e, results) => cb(results);
    ipcRenderer.on('party-results', listener);
    return () => ipcRenderer.removeListener('party-results', listener);
  },
  partyState: () => ipcRenderer.invoke('party-state'),
  partyOpenDisplay: () => ipcRenderer.invoke('party-open-display'),
  partyCastMiracast: () => ipcRenderer.invoke('party-cast-miracast'),
  partyExtendDisplay: () => ipcRenderer.invoke('party-extend-display'),
  partySetNightMode: isNightMode => ipcRenderer.invoke('party-set-night-mode', isNightMode),
  partyFindTvs: () => ipcRenderer.invoke('party-find-tvs'),
  partyCastSamsung: address => ipcRenderer.invoke('party-cast-samsung', address),
  onParty: cb => ipcRenderer.on('party', (_e, state) => cb(state)),
  save: (uid, fields) => ipcRenderer.invoke('save', uid, fields),
  createQuestion: fields => ipcRenderer.invoke('create-question', fields),
  deleteQuestion: uid => ipcRenderer.invoke('delete-question', uid),
  exportOwnQuestions: () => ipcRenderer.invoke('export-own-questions'),
  importOwnQuestions: () => ipcRenderer.invoke('import-own-questions'),
  exportList: listId => ipcRenderer.invoke('export-list', listId),
  importList: () => ipcRenderer.invoke('import-list'),
  pickQuestionImage: (uid, column) => ipcRenderer.invoke('pick-question-image', uid, column),
  removeQuestionImage: (uid, column) => ipcRenderer.invoke('remove-question-image', uid, column),
  onUpdate: cb => ipcRenderer.on('update', (_e, status) => cb(status)),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  dataSources: () => ipcRenderer.invoke('data-sources'),
  updateDataSource: (id, mode) => ipcRenderer.invoke('update-data-source', id, mode),
  stopDataSource: () => ipcRenderer.invoke('stop-data-source'),
  deleteDataSource: id => ipcRenderer.invoke('delete-data-source', id),
  onDataSourceProgress: cb => {
    const listener = (_e, progress) => cb(progress);
    ipcRenderer.on('data-source-progress', listener);
    return () => ipcRenderer.removeListener('data-source-progress', listener);
  },
});
