'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  info: () => ipcRenderer.invoke('info'),
  search: opts => ipcRenderer.invoke('search', opts),
  get: uid => ipcRenderer.invoke('get', uid),
  aiStatus: () => ipcRenderer.invoke('ai-status'),
  setAiSearch: isOn => ipcRenderer.invoke('set-ai-search', isOn),
  onAi: cb => ipcRenderer.on('ai', (_e, status) => cb(status)),
  gameQuestions: n => ipcRenderer.invoke('game-questions', n),
  lists: () => ipcRenderer.invoke('lists'),
  createList: name => ipcRenderer.invoke('create-list', name),
  renameList: (listId, name) => ipcRenderer.invoke('rename-list', listId, name),
  deleteList: listId => ipcRenderer.invoke('delete-list', listId),
  addToList: (listId, uid) => ipcRenderer.invoke('add-to-list', listId, uid),
  removeFromList: (listId, uid) => ipcRenderer.invoke('remove-from-list', listId, uid),
  reorderList: (listId, uidsInOrder) => ipcRenderer.invoke('reorder-list', listId, uidsInOrder),
  listQuestions: listId => ipcRenderer.invoke('list-questions', listId),
  listIdsContaining: uid => ipcRenderer.invoke('list-ids-containing', uid),
  startPlayGame: settings => ipcRenderer.invoke('start-play-game', settings),
  submitPlayAnswer: (gameId, answer) => ipcRenderer.invoke('submit-play-answer', gameId, answer),
  setPlayAnswerCorrect: (gameId, position, isCorrect) => ipcRenderer.invoke('set-play-answer-correct', gameId, position, isCorrect),
  finishPlayGame: gameId => ipcRenderer.invoke('finish-play-game', gameId),
  deletePlayGame: gameId => ipcRenderer.invoke('delete-play-game', gameId),
  playGames: () => ipcRenderer.invoke('play-games'),
  playGameAnswers: gameId => ipcRenderer.invoke('play-game-answers', gameId),
  partyOpen: () => ipcRenderer.invoke('party-open'),
  partyStartRound: round => ipcRenderer.invoke('party-start-round', round),
  partySkipWait: () => ipcRenderer.invoke('party-skip-wait'),
  partyPause: () => ipcRenderer.invoke('party-pause'),
  partyResume: () => ipcRenderer.invoke('party-resume'),
  partySetScreen: screen => ipcRenderer.invoke('party-set-screen', screen),
  partyCloseAnswers: () => ipcRenderer.invoke('party-close-answers'),
  partyNext: () => ipcRenderer.invoke('party-next'),
  partyFinishRound: () => ipcRenderer.invoke('party-finish-round'),
  partySetCorrect: (playerId, position, isCorrect) => ipcRenderer.invoke('party-set-correct', playerId, position, isCorrect),
  partyKick: playerId => ipcRenderer.invoke('party-kick', playerId),
  partyBackToLobby: keepScores => ipcRenderer.invoke('party-back-to-lobby', keepScores),
  partyClose: () => ipcRenderer.invoke('party-close'),
  partyState: () => ipcRenderer.invoke('party-state'),
  partyOpenDisplay: () => ipcRenderer.invoke('party-open-display'),
  partyCastMiracast: () => ipcRenderer.invoke('party-cast-miracast'),
  partyExtendDisplay: () => ipcRenderer.invoke('party-extend-display'),
  partySetNightMode: isNightMode => ipcRenderer.invoke('party-set-night-mode', isNightMode),
  partyFindTvs: () => ipcRenderer.invoke('party-find-tvs'),
  partyCastSamsung: address => ipcRenderer.invoke('party-cast-samsung', address),
  onParty: cb => ipcRenderer.on('party', (_e, state) => cb(state)),
  save: (uid, fields) => ipcRenderer.invoke('save', uid, fields),
  createQuestion: fields => ipcRenderer.invoke('create-question', fields),
  deleteQuestion: uid => ipcRenderer.invoke('delete-question', uid),
  onUpdate: cb => ipcRenderer.on('update', (_e, status) => cb(status)),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  refresh: mode => ipcRenderer.invoke('refresh', mode),
  cancelRefresh: () => ipcRenderer.invoke('cancel-refresh'),
  onRefresh: cb => ipcRenderer.on('refresh', (_e, progress) => cb(progress)),
});
